name = 'shopify-oms'
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# This is a minimal config for Cloudflare Pages
# Environment variables should be set in the Cloudflare Pages dashboard