name = "shopify-oms-tax-invoice"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

# Workers Logs
[observability]
enabled = true

# Environment variables (non-sensitive)
[vars]
NODE_ENV = "production"

# KV Namespaces for caching (optional)
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "your-kv-namespace-id" # Replace with your actual KV namespace ID

# R2 bucket bindings (if needed for static assets)
# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "your-bucket-name"

# Routes configuration
routes = [
  { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
]

# Production environment
[env.production]
name = "shopify-oms-tax-invoice-production"
vars = { NODE_ENV = "production" }

# Staging environment
[env.staging]
name = "shopify-oms-tax-invoice-staging"
vars = { NODE_ENV = "staging" }

# Build configuration
[build]
command = "pnpm build:cloudflare"

# Static assets
[site]
bucket = ".open-next/assets"

# Limits and quotas
[limits]
cpu_ms = 50

# Triggers and crons (if needed)
# [[triggers.crons]]
# crons = ["0 0 * * *"]